### ISSUE TITLE
Documentation on how to use it? 

### ISSUE THREAD

**Issue by rjain15** [captray/react-print#1]
Hi, 

Can you have a example or doc (InvoicePrint) on how to use this react-print library. 

Thanks

**Comment by captray** [comment]
Sure thing. I will add it to the home page when I get the chance.

**Comment by captray** [comment]
I've added some sample code to the home page and I also added a demo directory. If you npm-install react-print, you can navigate to that directory in node_modules to see how it works. You should be able to open that demo index.html and hit Ctrl + P to open the print preview in Chrome and FireFox. In IE, you have to access Print Preview view a button or settings in the print pane. Let me know if you have additional questions.

**Comment by 404sand808s** [comment]
Hey, this is a very cool repo. I def want to use it.

I'm a bit confused on how to myself as well though. Considering we need to add react-no-print on every div that is not to be printed and considering that my application is actually quite nested, I'm wondering what you'd suggest to print something from a complex GUI? Like open in another window and print from there?

Thanks for this though.
